let mapleader = ' '

" Add fzf as runtime path
" if executable('fzf')
"   set rtp+=/usr/local/opt/fzf
" endif

if &loadplugins
  " Navigation
  " packadd! fzf.vim
  packadd! vim-asterisk
  packadd! vim-dirvish
  packadd! vim-eunuch
  packadd! vim-sneak
  packadd! vim-unimpaired

  " telescope
  packadd! popup.nvim
  packadd! plenary.nvim
  packadd! telescope.nvim

  " Git
  packadd! vim-fugitive
  packadd! vim-gitgutter

  " Comments gcc
  packadd! vim-commentary
  packadd! vim-context-commentstring

  " Syntax highlighting
  packadd! nvim-treesitter
  packadd! vim-graphql
  packadd! vim-pug
  packadd! vim-styled-components
  packadd! Jenkinsfile-vim-syntax

  " Conquer of Completion
  " packadd! coc.nvim

  " lsp completion for nvim
  if has('nvim')
    packadd! completion-nvim
    packadd! nvim-lsp
    packadd! diagnostic-nvim
  endif

  " Enhancements
  packadd! snippets.nvim
  packadd! vim-highlightedyank
  packadd! auto-pairs
  packadd! indentLine
  packadd! vim-surround
  packadd! is.vim
  packadd! vim-prettier

  " Adds :Gbrowse
  packadd! vim-rhubarb

  " Theme
  packadd! night-owl.vim
  packadd! vim-nightfly-guicolors
  packadd! vim-moonfly-colors
  " packadd! forest-night

  " Automatically reload files
  packadd! vim-autoread
endif

" Automatic, language-dependent indentation, syntax coloring and other
" functionality.
"
" Must come *after* the `:packadd!` calls above otherwise the contents of
" package "ftdetect" directories won't be evaluated.
filetype plugin indent on
syntax enable
set termguicolors

" let g:forest_night_enable_italic = 1
" let g:forest_night_disable_italic_comment = 1
" let g:forest_night_transparent_background = 1
" colorscheme forest-night

" colorscheme nightfly
colorscheme moonfly
" colorscheme night-owl
" Color Overrides
hi jsTemplateString  guifg=#addb67 guibg=NONE gui=NONE
hi xmlAttrib         guifg=#addb67 guibg=NONE gui=italic
hi clear TabLine
hi clear TabLineFill
hi link TabLineFill CursorLineNr
hi link TabLine CursorLineNr
hi! Normal ctermbg=NONE guibg=NONE
hi! NonText ctermbg=NONE guibg=NONE guifg=NONE ctermfg=NONE

" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL

" TODO
" 1. Set Jenkinsfile to groovy ' set ft=groovy' and remove Jenkins-vim-syntax


" Testing
" npx es-check es5 './index.js'
function! ES5Check()
  execute '20split | term npx es-check es5 "./index.js"'
endfunction

