require "hotrod.options"
require "hotrod.keymaps"
require "hotrod.plugins"
require "hotrod.surround"
require "hotrod.colorscheme"
require "hotrod.scroll"
require "hotrod.illuminate"
require "hotrod.completion"
require "hotrod.lsp.lspsaga"
require("hotrod.lsp.mason")
require "hotrod.lsp"
-- require "hotrod.lightbulb"
require "hotrod.treesitter"
require "hotrod.indent-blankline"
require "hotrod.telescope"
require "hotrod.comment"
require "hotrod.better-comments"
require "hotrod.autopairs"
require "hotrod.gitsigns"
require "hotrod.nullls"
require "hotrod.maximize"
require "hotrod.color"
require "hotrod.feline"
require "hotrod.fidget"
require "hotrod.leap"
require "hotrod.autocommands"
require "hotrod.resize"
require "hotrod.dirvish"
